name: Type Check

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/typecheck.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/typecheck.yml'

jobs:
  type-check:
    name: Type Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
        include:
          - os: windows-latest
            arch: x64
          - os: windows-11-arm
            arch: arm64
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      
      - name: Set up Python
        run: uv python install 3.10
      
      - name: Cache Python installation
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-${{ matrix.arch }}-python-3.10-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-python-3.10-
      
      - name: Install dependencies
        run: uv sync --all-extras --dev
      
      - name: Run type checking
        run: |
          if [ "${{ matrix.arch }}" = "x64" ]; then
            uv run ty check --exclude src/fluid_server/runtimes/qnn_whisper.py
          else
            uv run ty check
          fi
        shell: bash